const data = [
  {
    id: 1,
    disease: "cancer",
    cause:
      "Cancer is a group of diseases involving abnormal cell growth which can spread to other parts of the body. It can be brought about by factors like smoking, overweight, too much ultraviolet from the sun, poor diet, alcohol, lack of physical activity, pollution, infections, hormonal changes, genetics and so many others. There are over 200 cancer types and each depend on where is infected forexample leukemia which start in blood-forming tissues, skin cancer which infect the skin, breast cancer, lung cancer, colon cancer, etc. There are mainly four stages of cancer.",
    treatment:
      "Cancer is known as a fatal disease because most of the time patients die. It has been treated by surgery, chemotherapy, radiation therapy and the bone marrow and stem cell transplant. The STC30 is a modern simplified treatment for cancer, it is based on the stem cell treatment. Cancer is caused by DNA mutation and multiplication of abnormal cells, the STC30 stimulates the body to produce more cells to replace the damaged ones, nourish the healthy cells and fight off the abnormal cells which in turn reduces them to zero. The STC30 can eradicate cancer of any type within 2-6 months depending on the level it is about.",
  },
  {
    id: 2,
    disease: "Ulcers",
    cause:
      "Stomach ulcers also known as gastric ulcers are painful sores in the stomach lining. They are a type of peptic ulcer disease which affect both the stomach and the small intestines. Stomach ulcers occur when the thick layer of mucus that protects your stomach from digestive juices is reduced which allows these acids to eat away at the tissues that line the stomach causing an ulcer. The causes of stomach ulcers include; the Helicobacter pylori bacteria, a class of pain killers called non-steroidal anti-inflammatories, excess stomach acidity which maybe brought about by stress, smoking, genetics and some foods, Zollinger-Ellison disease. Certain behaviours and factors increase the chances of developing stomach ulcers which include frequent steroid usage, over consuming of alcohol, genetics, smoking, overproducing calcium-hypercalcemia. Symptoms; heartburn, loss of appetite, burning pain in the stomach between meals, nausea, bloating, dark stool.",
    treatment:
      "The STC30 is proven to treat ulcers 100%. It strengthens the immune system, stimulate production of intestinal cells, repairs damaged tissues in the stomach and prevent digestive acids from taking action by strengthening the mucous cells.",
  },
  {
    id: 3,
    disease: "hypertension",
    cause:
      "Hypertension also known as high blood pressure is when the pressure of the blood being pumped through the arteries is higher than it should be. Each time the heart beats, blood is pumped through the arteries and veins. Arterial pressure is created by the force exerted by thr blood against the artery walls, as they carry blood around the body. Hyprtension is a silent killer because it often has no warnings and many people are not aware of it in them. And overtime the constant pressure overload causes accumulating damage tht eventually becomes more than the circulatory system can handle, often leading to serious health problems. Blood pressure is divided into four categories; Normal blood prssure which is below 120/80 mm Hg, Prehypertension - 120-139 / 80-89 mm Hg, Stage One Hypertension - 140-159 / 90-99 mm Hg, Stage Two Hypertension - 160 / 100 mm Hg or higher. Types of hypertension; primary, secondary, malignant, resistant, pulmonary and pseudo hypertension. Risk factors include; genetics, hormone problems, lupus, age, lifestyle choices, certain medicatins, kidney disorders and obstructive sleep apnoea.",
    treatment:
      "Hypertension can be prevented by mantaining a healthy weight, exercising regularly, reducing salt intake, alcohol moderation, managing stress, nutrients like pottasium, magnesium and calcium, fish oils, garlic. Long term hypertension can lead to heart failure and heart attacks, stroke, bleeding and blindness. The STC30 has the ability to repair the cells responsible for the blood pressure, the endothelial cells and the muscle cells attached to the free blood pressure movement. It will also decrease blood lipid, blood viscousity, prevent platelet aggregation, prevent excessive blood clotting, reduce the risk of atherosclerosis, inhibit the thickening of arteries, dilate and relaxe arteries lower blood cholesterol level, prevent age-related muscular degeneration. It will stabilize the blood pressure from the root cause.",
  },
  {
    id: 4,
    disease: "pneumonia",
    cause:
      "Pneumonia is an infection that inflames the air sacs in one or both lungs. During infection, the alveoli of one or both lungs fill up with pus or fluid and it increases the work of breathing and thus gaseous exchange in the lungs can't occur at it normally would. The body has defense mechanisms against the agents of pneumonia ie, coughing, mucociliary escalator, macrophages. If these mechanisms fail and a microbe succeeds in colonizing the alveoli, they multiply and quickly move over in to the lung tissue activating an inflammatory response and the result is pneumonia. Signs and symptoms; headache, vomiting, difficulty breathing, dehydration, fever, chills, coughing, muscle pains, malaise, loss of appetite.",
    treatment:
      "People with a weakened immune system are at a high risk of acquiring pneumonia. Other risk factors include; smoking, flu, cancer, heart disease, stroke, chronic bronchitis, asthma. The STC30 manages and treats pneumonia. It strengthens the immune system, stimulate the macrophages and reduce lung inflammation and it can fully regenerate the respiratory system. ",
  },
  {
    id: 5,
    disease: "stroke",
    cause:
      'Stroke is one of the leading causes of disability in adults and 5th among the causes of disease burden in developing countries. A stroke is a "brain attack". It can happen to anyone at anytime. It occurs when blood flow to an area of the brain is cut off. When this happens, the brain cells are deprived of oxygen and begin to die. When brain cells die, abilities controlled by that area of the brain such as memory and muscle control are lost. There are mainly two types of stroke, ie, Ischemic stroke which happens when a bood clot keeps blood from flowing to the brain and Hemorrhagic stroke which occurs when a blood vessel in your brain ruptures or breaks, spilling blood into the surrounding areas. The most common risk factors are high blood pressure, high cholesterol, heart problems, smoking, diabetes and increasing age. Symptoms of stroke include; double vision, one sided paralysis, change in the level of consciousness or confusion, difficulty with balance, face dropping, difficulty speaking and swallowing, partial vision and convulsions.',
    treatment:
      "Stroke can be prevented by managing diabetes, keeping blood pressure under control, eating a healthy diet, mantaining a healthy weight and avoiding alcohol. Until recently, brain tissue damage was considered permanent but now with the stem cell treatment, there can be brain cell regrowth and improvement in the neurological function. The STC30 activates cells around the affected brain tissue to catalyze rapid healing and improve brain function. It also boosts, regenerate nerve cells around the affected areas which improves motor function. The STC30 manages and treats stroke 100%",
  },
  {
    id: 6,
    disease: "diabetes",
    cause:
      "Diabetes is a disease that occurs when the blood sugar (glucose) is too high. Blood glucose is the main source of energy and comes from the foods one eat. Insulin, a hormone made by the pancreas, helps glucose from food get into the cells to be used for energy. Types of diabetes; Type 1, this occurs when the body fails to produce insulin. People with type 1 diabetes take in artificial insulin to stay alive. Type 2 diabetes, affects the way the body uses insulin. While the body still makes insulin, the cells in the body do not respond to it effectively as it normally would and this is the most common type of diabetes. The exact cause of type 1 diabetes is unknown. Usually, the body's own immune system which normally fights harmful bacteria and viruses mistakenly destroy the insulin producing cells in the body. Type 2, the exact cause isn't known but lifestyle choices, genetics and the environment plays a big role. Symptoms include frequent urination, unclear eye sight, increased hunger, wounds that don't heal, thirst, swollen gums, sudden weight loss, dark skin. ",
    treatment:
      "Diabetes can lead to nerve damage, heart disease, eye damage, weight loss, hearing impairment, stroke, foot damage, kidney damage and dental problems. The currently available treatments can control diabetes to a certain level but can't heal it completely and one has to use them for all life. But the stem cell therapy has been so effective in treating diabetes because it helps remove excess blood sugar, rejuvenates the pancreas and differentiate or regenerates into the pancreatic beta-islet cells to produce more insulin and also brings balance to the immune system so that it stops rejecting the insulin.",
  },
  {
    id: 7,
    disease: "sickle cells",
    cause:
      "Sickle cells is a group of inherited red blood disorders. It occurs after inheritance of two sickle cell genes from parents. People with sickle cells have an abnormal protein in their red blood cells (hemoglobin). Red blood cells are usually round and flexible and can move easily through blood vessels but in sickle cell anemia, the red blood cells are shaped like a sicke or crescent moons and can get stuck in small blood vessels slowing or stopping blood flow and oxygen to parts of the body. Sypmtoms include; fatigue, delayed growth, pain, swelling and inflammation of hands and feet, sudden pooling of blood in the spleen and liver congestion, lung and heart injury, leg wounds, eye damage and vision problems.;",
    treatment:
      "Sickle cells can be treated by a stem cell or bone marrow transplant. The person with sickle cells has bone marrow that produces red blood cells with defective hemoglobin which is then replaced by a healthy one got from a donor. The stem cell therapy STC30 is proven to cure sickle cells. It stimulates the body's stem cells, replicate cells and replace damaged or dead cells. The STC30 enables the body to produce healthy red blood cells replacing defective ones.",
  },
  {
    id: 8,
    disease: "hair loss (baldness)",
    cause:
      "The loss of hair from part of the head or body interferes with the many useful biological functions of the hair including sun protection and dispersal of swaet gland products. Each strand of hair is a complex weaving of lifeless protein produced by a teardrop-shaped hair follicle. Thr hair follicles are made of living cells that receive nourishment entirely from the blood supply under the skin. The hair itself is made up of completely dead cells. Types of hair loss; *Involutional alopecia, a natural conditon in which the hair gradually thins with age. More hair follicles go into resting phase, and the remaining become shorter and few in number. *Androgenic alopecia is a genetic condition that can affect both men and women. Men with this condition can begin suffering hair loss as early as their teens or early 20s. It is characterised by a receding hairline and gradual diasappearance of hair from the crown and frontal scalp. Women with this condition dont't experience noticeable thinning until their 40s or later. *Alopecia areata often starts suddenly and causes patchy hair loss in children and young adults. This condition may result in complete baldness. But in about 90% of people with the condition, the hair returns within a few years. *Alopecia universalis causes all body hair to fall out, including eyebrows, eyelashes and the pubic hair. *Trichotillomania, seen most frequently in children, is a psychological disorder in which a person pulls out one's own hair. *Telogen effluvium is temporary hair thinning over the scalp that occurs because of changes in the growth cycle of hair. *Scarring alopecias result in result in permanent loss of hair. Inflammatory skin conditions and disorders often result in scars that destroy the ability of the hair to regenerate. Hot combs and hair too tightly woven and pulled can also result in permanent hair loss. Causes and risk factors include; physical stress, hairstyles and hair treatment, poor nutrition, hormonal changes, aging, family background, chemotherapy, medications and supplements, emotional stress.",
    treatment:
      "Symptoms and signs; gradual thinning on top of the head, patchy bald spots, full body hair loss, sudden loosening of hair. The stem cell therapy is a process which has given proven results. It is an efficient, non-surgical therapy that stimulates and regrow hair follicles. Stem cells in the follicles ensure the continous supply of cells and helps multiplying hair cells on a fast pace. Thus the stem cells not only helps to fight the hair loss but also improves the texture and hair quality",
  },
  {
    id: 9,
    disease: "Goitre",
    cause:
      "A goitre is an enlargement of the thyroid gland, a butterfly-shaped gland which is present at the front of the throat and below the Adam’s apple. Goitre is classified as diffuse or nodular. In diffuse goitre the whole thyroid gland swells and its smooth to touch. And in nodular goitre, solid or fluid-filled lumps called thyroid nodules develop in the thyroid gland. Nodular goitre is further classified into two types; Uninodular with only one nodule. *Multinodular with more than one nodule. *The nodules may be inactive or toxic. Goitre may also be classified as endemic and sporadic. Endemic goitre occurs due to insufficient dietary iodine intake and in sporadic goitre, the cause is unknown.",
    treatment:
      "Goitre can be caused by lack of iodine, autoimmune disorders like graves' disease, pregnancy, family background, radiation exposure, some medication, aging, thyroid cancer, thyroiditis. Signs and symptoms; Swelling in front of the neck, tightness in the neck,   hair loss,  difficulty breathing, dry skin, weight gain/weight loss, hoarseness, difficulty swallowing,  rapid heartbeat, forgetfulness, etc. With the stem cell therapy (STC30) you can get treated from goitre. The STC30 has large amounts of iodine, it boosts your immune system against autoimmune disorders and it will regenerate your thyroid gland by stimulating thyroid stem cells that produce thyroid hormones and help maintain thyroid hormones.",
  },
  {
    id: 10,
    disease: "Heart Disease",
    cause:
      "Heart disease (cardiovascular diseases) are conditions that affect the structure and functions of the heart. Heart disease types; *Coronary artery heart disease that affects the arteries to the heart. *Valvular heart disease that affects how the valves function to regulate blood flow in and out of the heart. *Cardiomyopathy that affects how the heart muscle squeezes. *Heart rhythm disturbances that affect the electrical conduction. *Heart infections where the heart has structural problems that develop before birth. Causes of heart disease; Thickening of artery walls, high blood pressure, enlarging of the heart muscle, reduced blood flow to the heart, diabetes, smoking, excessive use of alcohol or caffeine, drug abuse, stress, some medications, infections, age, chemotherapy, family history, poor diet, obesity, physical inactivity, poor hygiene.  ",
    treatment:
      "Sometimes you might not be diagnosed with heart disease until you have a heart attack, angina, stroke or heart failure so it's important to watch for cardiovascular symptoms. Heart disease symptoms depend on what type of heart disease you have and they may be different for men and women and they include; chest pain, tightness and pressure, shortness of breath, pain, numbness, weakness or coldness in the legs or arms, pain in the neck, jaw, throat, upper abdomen or back, racing heartbeat, slow heartbeat, lightheadedness, dizziness, fainting, pale gray or blue skin color, swelling in the legs, abdomen or areas around the eyes. Heart disease can lead to heart failure, heart attack, stroke, aneurysm, cardiac arrest. With the stem cell therapy (STC30) you can be totally treated of heart disease. With respect to the heart, stem cells have the ability to not only home into the damaged areas but also to initiate a cascade of biological events which both culminate in healing of the heart muscle. The stem cell will cause new muscle cells to be formed through stimulation of dormant stem cells that are already inside the heart muscle and also the administered stem cell will also transform into new heart muscle cells. Since the STC30 is immune system privileged, cell rejection is not an issue and Human Leukocyte Antigen (HLA) matching is not necessary. Through administration of the stem cell therapy (STC30), there's improvements in heart disease patients.",
  },
  {
    id: 11,
    disease: "fibroids",
    cause:
      "Fibroids are abnormal growths that develop in or on a woman's uterus. They are non cancerous and appear during child bearing years. Fibroids range in size from seedlings undetectable by the human eye to bulky masses that can distort and enlarge the uterus. It's estimated that 70-80% women will grow fibroids in their lifetime. The cause of uterine fibroids isn't know but research and clinical experience point to genetic changes, extracellular matrix, hormones and other growth factors. Risk factors are age, family history and obesity. Most women with fibroids will experience no symptoms at all. However, large or numerous fibroids can cause symptoms; Heavy or prolonged periods, bleeding between periods, pelvic pain and pressure, frequent urination, low back pain, pain during intercourse, difficulty getting pregnant",
    treatment:
      "Although fibroids usually aren't dangerous but they can cause discomfort and may lead to complications such as a drop in red blood cells (anemia), which causes fatigue, from heavy blood loss and sometimes pregnancy loss and infertility. Common treatment is usually associated with side effects like irregular periods, acne, osteoporosis, adhesion, scars, and a re-growth of fibroid after surgery but with the stem cell therapy (STC30) you can treat fibroids from the root cause. The STC30 will shrink fibroid tissues, balance the body hormones, detoxify the body of toxins and regenerate fresh healthy tissues to fix damaged tissues. The STC30 will also activate body stem cells to regenerate and revitalize patients internal organs/tissues unspecifically, as well as activate existing stem cells. These processes prevent a fibroid regrowth with no side effect and a 99.9% success rate.",
  },
]

export default data
